export const FETCH_POPULAR_TV = 'FETCH_POPULAR_TV';
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TV_GENRES = 'FETCH_TV_GENRES';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';
export const FETCH_FEATURED_LISTS = 'FETCH_FEATURED_LISTS';
